Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ContactUs.Validation;

namespace ContactUs.Controllers
{
    public class ContactUsController : Controller
    {
        // GET: ContactUs
        public ActionResult Index()
        {
            return View(EmptyContact());
        }

        /// <summary>
        ///     Contact us form submission
        /// </summary>
        /// <param name="collection"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(FormCollection collection)
        {
            Contact contact = new Contact();
            TryUpdateModel(contact);
            contact.BestTimeToCall = ConvertTimeInput(collection["Hour"], collection["Minute"], collection["Meridiem"]);

            bool success = false;
            Dictionary<String, String> disclaimers = new Dictionary<string, string>();

            string EncodedResponse = Request.Form["g-Recaptcha-Response"];
            bool IsCaptchaValid = EncodedResponse != null ? (Recaptcha.Validate(EncodedResponse)) : false;

            Dictionary<String, List<String>> validationErrors = ContactValidation.Validate(contact);
            ViewData["ValidationErrors"] = validationErrors;

            if (validationErrors.Count == 0)
            {
                if (IsCaptchaValid)
                {
                    using (var db = new ContactUsEntities())
                    {
                        db.Contacts.Add(contact);
                        db.SaveChanges();
                        success = true;
                        disclaimers.Add("success", "Your form has been successfully submitted!");
                    }
                }
                else
                {
                    disclaimers.Add("warning", "ReCAPTCHA is invalid. Please try reCAPTCHA again!");
                }
            }

            ViewData["Disclaimers"] = disclaimers;
            return success ? View(EmptyContact()) : View(contact);
        }
        
        /// <summary>
        ///     Convert individual time inputs into one DateTime
        /// </summary>
        /// <param name="hour"></param>
        /// <param name="min"></param>
        /// <param name="meridiem"></param>
        /// <returns></returns>
        public DateTime ConvertTimeInput(string hour, string min, string meridiem)
        {
            if (String.IsNullOrEmpty(hour))
                hour = "00";
            if (String.IsNullOrEmpty(min))
                min = "00";
            string time = hour + ":" + min + meridiem;
            return Convert.ToDateTime(time);
        }
        
        /// <summary>
        ///     Create empty contact for new form loads
        /// </summary>
        /// <returns></returns>
        public Contact EmptyContact()
        {
            Contact contact = new Contact();
            contact.BestTimeToCall = Convert.ToDateTime("9:00:00AM");
            return contact;
        } 
    }
}

Views/ContactUs/index.cshtml
@model Contact
@{
    ViewBag.Title = "Contact Us";
    Layout = "~/Views/Shared/_layout.cshtml";
}
@Scripts.Render("~/bundles/js")

<div class="info">
    <span>
        <div class="content">
            <h1>Let's Chat!</h1>
            <p>
                Feel free to schedule a time to talk with us! We welcome all types of questions and would love to discuss them with you.
                Our business hours are listed below, and anytime within that time range in 15 minute increments will work fine with us.
                Leave your first and last name, email, phone number, and best time for you to talk, and we'll get back to you shortly.
            </p>
            <p>
                Looking forward to speaking with you!
            </p>
            <span class="spec">
                <h3>
                    <i class="fas fa-map-marker-alt"></i>
                    Dallas, TX
                </h3>
                <h3>
                    <i class="fas fa-clock"></i>
                    9:00am - 6:00pm
                </h3>
            </span>
        </div>
    </span>
</div>
<div class="form">
    <span>
        <div class="disclaimer">
            @{
                if (ViewData["Disclaimers"] != null && ((Dictionary<String, String>)ViewData["Disclaimers"]).Count() > 0)
                {
                    Dictionary<String, String> disclaimers = (Dictionary<String, String>)ViewData["Disclaimers"];
                    foreach (KeyValuePair<String, String> kvp in disclaimers)
                    {
                        <div class="message @kvp.Key">
                            <p>@kvp.Value</p>
                        </div>
                    }
                }
            }
            @{if (ViewData["ValidationErrors"] != null && ((Dictionary<String, List<String>>)ViewData["ValidationErrors"]).Count() > 0)
              {
                    <div class="message warning">
                    <p>
                    @{
                        Dictionary<String, List<String>> validationErrors = (Dictionary<String, List<String>>)ViewData["ValidationErrors"];
                        foreach (KeyValuePair<String, List<String>> kvp2 in validationErrors)
                        {
                            @kvp2.Value.FirstOrDefault()
                            <br />
                        }
                    }
                    </p>
                </div>
              }
                
            }
        </div>
        <div class="content">
            @using (Html.BeginForm("Index", "ContactUs", FormMethod.Post))
            {
                @Html.TextBox("FirstName", Model.FirstName, new { @class = "col-50 ", placeholder = "First Name" })
                @Html.TextBox("LastName", Model.LastName, new { @class = "col-50 ", placeholder = "Last Name", style = "float:right" })
                @Html.TextBox("EmailAddress", Model.EmailAddress, new { @class = "col-100 ", placeholder = "Email", type = "email" })
                @Html.TextBox("Telephone", Model.Telephone, new { @class = "col-100 ", placeholder = "Phone Number" })

                <label id="time_label" class="col-50">Time:</label>
                <div id="time">
                    @Html.TextBox("Hour", Model.BestTimeToCall.Value.ToString("hh"), new { maxlength = "2" })    
                    <label style="float: left">:</label>
                    @Html.TextBox("Minute", Model.BestTimeToCall.Value.ToString("mm"), new { maxlength = "2" })
                    @Html.TextBox("Meridiem", Model.BestTimeToCall.Value.ToString("tt"), new { @readonly = "true" })
                </div>

                <div class="g-recaptcha" data-sitekey="6LcsgWoUAAAAAAGN7ynvqls2GW9qzIwy_CBLtci6"></div>

                <button id="submit" type="submit" value="Submit">SUBMIT</button>
                @Html.AntiForgeryToken()
            }
        </div>
    </span>
</div>

Views/Shared/_layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/bundles/css")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
</head>
<body>

    @RenderBody()

</body>
</html>